services:
  app:
    image: nalekseev2306/fastapi-homework
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - '127.0.0.1:8020:8000'
    build:
      context: .
    pull_policy: build
    entrypoint: sh -c "./src/start.sh"
