"""init postgres db

Revision ID: be493ec92225
Revises: 
Create Date: 2026-05-03 11:26:43.804051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from src.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'be493ec92225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('description', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('slug', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_categories_slug'), 'categories', ['slug'], unique=True, schema='application')
    op.create_table('locations',
    sa.Column('name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_locations_name'), 'locations', ['name'], unique=True, schema='application')
    op.create_table('users',
    sa.Column('username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('password', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('first_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('last_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_users_email'), 'users', ['email'], unique=True, schema='application')
    op.create_index(op.f('ix_application_users_username'), 'users', ['username'], unique=True, schema='application')
    op.create_table('posts',
    sa.Column('title', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('text', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['application.categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['application.locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['application.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_posts_category_id'), 'posts', ['category_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_posts_location_id'), 'posts', ['location_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_posts_user_id'), 'posts', ['user_id'], unique=False, schema='application')
    op.create_table('comments',
    sa.Column('text', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['application.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['application.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_comments_post_id'), 'comments', ['post_id'], unique=False, schema='application')
    op.create_index(op.f('ix_application_comments_user_id'), 'comments', ['user_id'], unique=False, schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_comments_user_id'), table_name='comments', schema='application')
    op.drop_index(op.f('ix_application_comments_post_id'), table_name='comments', schema='application')
    op.drop_table('comments', schema='application')
    op.drop_index(op.f('ix_application_posts_user_id'), table_name='posts', schema='application')
    op.drop_index(op.f('ix_application_posts_location_id'), table_name='posts', schema='application')
    op.drop_index(op.f('ix_application_posts_category_id'), table_name='posts', schema='application')
    op.drop_table('posts', schema='application')
    op.drop_index(op.f('ix_application_users_username'), table_name='users', schema='application')
    op.drop_index(op.f('ix_application_users_email'), table_name='users', schema='application')
    op.drop_table('users', schema='application')
    op.drop_index(op.f('ix_application_locations_name'), table_name='locations', schema='application')
    op.drop_table('locations', schema='application')
    op.drop_index(op.f('ix_application_categories_slug'), table_name='categories', schema='application')
    op.drop_table('categories', schema='application')
    # ### end Alembic commands ###
